"""Tests for RFC 9380 hash-to-curve / hash-to-scalar."""

import hashlib

import pytest

from otrs.group import POINT_BYTES, SCALAR_BYTES, Point, Scalar
from otrs.hash import expand_message_xmd, hash_to_group, hash_to_scalar


class TestExpandMessageXmd:
    def test_output_length_exact(self):
        for L in [1, 32, 48, 64, 65, 128, 200, 1024]:
            out = expand_message_xmd(b"hello", b"DST", L)
            assert len(out) == L

    def test_deterministic(self):
        a = expand_message_xmd(b"msg", b"DST", 64)
        b = expand_message_xmd(b"msg", b"DST", 64)
        assert a == b

    def test_distinct_messages_diverge(self):
        a = expand_message_xmd(b"msg-a", b"DST", 64)
        b = expand_message_xmd(b"msg-b", b"DST", 64)
        assert a != b

    def test_distinct_dst_diverge(self):
        a = expand_message_xmd(b"same", b"DST-1", 64)
        b = expand_message_xmd(b"same", b"DST-2", 64)
        assert a != b

    def test_oversize_dst_hashed_per_spec(self):
        """RFC 9380 §5.3.3: DST > 255 bytes is hashed with the H2C-OVERSIZE prefix."""
        long_dst = b"X" * 300
        short_dst = hashlib.sha512(b"H2C-OVERSIZE-DST-" + long_dst).digest()
        assert expand_message_xmd(b"m", long_dst, 64) == expand_message_xmd(
            b"m", short_dst, 64
        )

    def test_invalid_length_rejected(self):
        with pytest.raises(ValueError):
            expand_message_xmd(b"m", b"D", 0)
        with pytest.raises(ValueError):
            expand_message_xmd(b"m", b"D", 70000)

    # Pinned regression vector. Recompute when changing the implementation.
    # These bytes were generated by this implementation on first run and are
    # included so that subsequent edits cannot silently change the output.
    # External cross-validation against RFC 9380 §K is on the test backlog.
    REGRESSION_DST = b"OTRS-TEST-V1-XMD:SHA-512-REGRESSION"

    def test_regression_vector_empty(self):
        out = expand_message_xmd(b"", self.REGRESSION_DST, 32)
        # Pin to the value produced by the spec-compliant implementation.
        # Generated on first run; pinned for regression.
        from tests.regression_vectors import EXPAND_XMD_EMPTY_32
        assert out.hex() == EXPAND_XMD_EMPTY_32


class TestHashToGroup:
    def test_returns_valid_point(self):
        p = hash_to_group(b"hello", b"DST")
        assert isinstance(p, Point)
        assert len(p.raw) == POINT_BYTES

    def test_deterministic(self):
        p1 = hash_to_group(b"msg", b"DST")
        p2 = hash_to_group(b"msg", b"DST")
        assert p1.raw == p2.raw

    def test_distinct_inputs_diverge(self):
        p1 = hash_to_group(b"msg-a", b"DST")
        p2 = hash_to_group(b"msg-b", b"DST")
        assert p1.raw != p2.raw

    def test_distinct_dst_diverge(self):
        p1 = hash_to_group(b"msg", b"DST-1")
        p2 = hash_to_group(b"msg", b"DST-2")
        assert p1.raw != p2.raw


class TestHashToScalar:
    def test_returns_valid_scalar(self):
        s = hash_to_scalar(b"hello", b"DST")
        assert isinstance(s, Scalar)
        assert len(s.raw) == SCALAR_BYTES

    def test_deterministic(self):
        s1 = hash_to_scalar(b"msg", b"DST")
        s2 = hash_to_scalar(b"msg", b"DST")
        assert s1.raw == s2.raw

    def test_distinct_inputs_diverge(self):
        s1 = hash_to_scalar(b"msg-a", b"DST")
        s2 = hash_to_scalar(b"msg-b", b"DST")
        assert s1.raw != s2.raw

    def test_distinct_dst_diverge(self):
        s1 = hash_to_scalar(b"msg", b"DST-1")
        s2 = hash_to_scalar(b"msg", b"DST-2")
        assert s1.raw != s2.raw
